### ISSUE TITLE
Meta-language selection does not stick

### ISSUE THREAD

**Issue by snomos** [divvun/satni-frontend#4]
To repeat:

1. go to satni.org, notice how the page is in North sami
2. set metalanguage to nynorsk
3. search something
4. close the browser window
1. go to satni.org once more
1. notice how the interface language is North Sami again

Expected: the interface language should have been Nynorsk when reopening the site.

Tested with Safari 13.1.2 on macOS 10.15.6.

**Comment by albbas** [comment]
This has been solved in ba5b6735c48e6d18e9a8ea9f33d8ad2807ab7e26
