### ISSUE TITLE
Article URL's return 404

### ISSUE THREAD

**Issue by snomos** [divvun/satni-frontend#69]
Example: https://satni.org/geađgi

Here's what I get in Safari:

![image](https://github.com/divvun/satni-frontend/assets/1255285/0ae79f1f-755f-4385-b372-863ed16953b9)

**Comment by albbas** [comment]
This was fixed by adding a rewrite rule for React router in the apache config:
    RewriteEngine On
    # Don't rewrite files or directories
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
    # Rewrite everything else to index.html to allow html5 state links
    RewriteRule ^ index.html [L]
